// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wtpsoiegeihvqmrawcjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind0cHNvaWVnZWlodnFtcmF3Y2pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MDcwMzEsImV4cCI6MjA2NjM4MzAzMX0.moI90EcV2mbBrIeuEUPVk8ZNsEm24Xl8LG1BIgbOJEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);